// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace FCS_Funding_Coded_UI_Tests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Tested logging into the program with a username of "admin" and a password of "Admin".
        /// </summary>
        public void LoginTest()
        {
            #region Variable Declarations
            WpfEdit uIUsernameEdit = this.UILoginWindow.UIUsernameEdit;
            WpfEdit uIPasswordEdit = this.UILoginWindow.UIPasswordEdit;
            WpfButton uILoginButton = this.UILoginWindow.UILoginButton;
            #endregion

            // Launch '%USERPROFILE%\Desktop\Spring2016\Software Engineering 3\FCS-Funding-2\FCS-Project\FCS_Funding_WPF\FCS_Funding\bin\Debug\FCS_Funding.exe'
            ApplicationUnderTest uILoginWindow = ApplicationUnderTest.Launch(this.LoginTestParams.UILoginWindowExePath, this.LoginTestParams.UILoginWindowAlternateExePath);

            // Type 'admin' in 'Username' text box
            uIUsernameEdit.Text = this.LoginTestParams.UIUsernameEditText;

            // Click 'Password' text box
            Mouse.Click(uIPasswordEdit, new Point(99, 27));

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.LoginTestParams.UIPasswordEditSendKeys, true);

            // Click 'Login' button
            Mouse.Click(uILoginButton, new Point(117, 9));
        }
        
        /// <summary>
        /// Tested inserting a patient.
        /// </summary>
        public void TestInsertPatient()
        {
            #region Variable Declarations
            WpfEdit uIUsernameEdit = this.UILoginWindow.UIUsernameEdit;
            WpfEdit uIPasswordEdit = this.UILoginWindow.UIPasswordEdit;
            WpfButton uILoginButton = this.UILoginWindow.UILoginButton;
            WpfButton uICreateNewPatientButton = this.UIMainWindowWindow.UIItemTabList.UIPatientsTabPage.UICreateNewPatientButton;
            WpfEdit uIItemEdit = this.UICreateNewPatientWindow.UIItemEdit;
            WpfEdit uIItemEdit1 = this.UICreateNewPatientWindow.UIItemEdit1;
            WpfEdit uIItemEdit2 = this.UICreateNewPatientWindow.UIItemEdit2;
            WpfEdit uIItemEdit3 = this.UICreateNewPatientWindow.UIItemEdit3;
            WpfCheckBox uIIsHeadofHouseholdCheckBox = this.UICreateNewPatientWindow.UIIsHeadofHouseholdCheckBox;
            WpfComboBox uIGenderComboBox = this.UICreateNewPatientWindow.UIGenderComboBox;
            WpfComboBox uIAgeGroupComboBox = this.UICreateNewPatientWindow.UIAgeGroupComboBox;
            WpfComboBox uIEthnicityComboBox = this.UICreateNewPatientWindow.UIEthnicityComboBox;
            WpfCheckBox uIFirstMemberofHousehoCheckBox = this.UICreateNewPatientWindow.UIFirstMemberofHousehoCheckBox;
            WpfButton uIAddClientButton = this.UICreateNewPatientWindow.UIAddClientButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            WpfEdit uIItemEdit4 = this.UICreateHouseholdWindow.UIItemEdit;
            WpfEdit uIItemEdit11 = this.UICreateHouseholdWindow.UIItemEdit1;
            WpfComboBox uIIncomeComboBox = this.UICreateHouseholdWindow.UIIncomeComboBox;
            WpfButton uIAddHouseholdButton = this.UICreateHouseholdWindow.UIAddHouseholdButton;
            WpfButton uIRefreshButton = this.UIMainWindowWindow.UIItemTabList.UIPatientsTabPage.UIRefreshButton;
            #endregion

            // Launch '%USERPROFILE%\Desktop\Spring2016\Software Engineering 3\FCS-Funding-2\FCS-Project\FCS_Funding_WPF\FCS_Funding\bin\Debug\FCS_Funding.exe'
            ApplicationUnderTest uILoginWindow = ApplicationUnderTest.Launch(this.TestInsertPatientParams.UILoginWindowExePath, this.TestInsertPatientParams.UILoginWindowAlternateExePath);

            // Type 'admin' in 'Username' text box
            uIUsernameEdit.Text = this.TestInsertPatientParams.UIUsernameEditText;

            // Type '{Tab}' in 'Username' text box
            Keyboard.SendKeys(uIUsernameEdit, this.TestInsertPatientParams.UIUsernameEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.TestInsertPatientParams.UIPasswordEditSendKeys, true);

            // Click 'Login' button
            Mouse.Click(uILoginButton, new Point(47, 21));

            // Click 'Create New Patient' button
            Mouse.Click(uICreateNewPatientButton, new Point(196, 51));

            // Type '50' in text box
            uIItemEdit.Text = this.TestInsertPatientParams.UIItemEditText;

            // Type 'codedUITest' in text box numbered 2 in 'CreateNewPatient' window
            uIItemEdit1.Text = this.TestInsertPatientParams.UIItemEdit1Text;

            // Type 'lastName' in text box numbered 3 in 'CreateNewPatient' window
            uIItemEdit2.Text = this.TestInsertPatientParams.UIItemEdit2Text;

            // Click text box numbered 4 in 'CreateNewPatient' window
            Mouse.Click(uIItemEdit3, new Point(106, 42));

            // Select 'Is Head of Household?' check box
            uIIsHeadofHouseholdCheckBox.Checked = this.TestInsertPatientParams.UIIsHeadofHouseholdCheckBoxChecked;

            // Select 'Female' in 'Gender' combo box
            uIGenderComboBox.SelectedItem = this.TestInsertPatientParams.UIGenderComboBoxSelectedItem;

            // Select '45-54' in 'AgeGroup' combo box
            uIAgeGroupComboBox.SelectedItem = this.TestInsertPatientParams.UIAgeGroupComboBoxSelectedItem;

            // Select 'Asian' in 'ethnicity' combo box
            uIEthnicityComboBox.SelectedItem = this.TestInsertPatientParams.UIEthnicityComboBoxSelectedItem;

            // Select 'First Member of Household?' check box
            uIFirstMemberofHousehoCheckBox.Checked = this.TestInsertPatientParams.UIFirstMemberofHousehoCheckBoxChecked;

            // Click 'Add Client' button
            Mouse.Click(uIAddClientButton, new Point(78, 26));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(83, 27));

            // Type 'Is head' in text box numbered 4 in 'CreateNewPatient' window
            uIItemEdit3.Text = this.TestInsertPatientParams.UIItemEdit3Text;

            // Click 'Add Client' button
            Mouse.Click(uIAddClientButton, new Point(141, 25));

            // Type '2' in text box
            uIItemEdit4.Text = this.TestInsertPatientParams.UIItemEditText1;

            // Type 'North Pole' in text box numbered 2 in 'CreateHousehold' window
            uIItemEdit11.Text = this.TestInsertPatientParams.UIItemEdit1Text1;

            // Select '$35,000+' in 'income' combo box
            uIIncomeComboBox.SelectedItem = this.TestInsertPatientParams.UIIncomeComboBoxSelectedItem;

            // Click 'Add Household' button
            Mouse.Click(uIAddHouseholdButton, new Point(165, 37));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(53, 26));

            // Click 'Refresh' button
            Mouse.Click(uIRefreshButton, new Point(210, 34));
        }
        
        /// <summary>
        /// Inserted an individual donor.
        /// </summary>
        public void TestInsertDonorIndividual()
        {
            #region Variable Declarations
            WpfEdit uIUsernameEdit = this.UILoginWindow.UIUsernameEdit;
            WpfEdit uIPasswordEdit = this.UILoginWindow.UIPasswordEdit;
            WpfButton uILoginButton = this.UILoginWindow.UILoginButton;
            WpfTabPage uIDonorsTabPage = this.UIMainWindowWindow.UIItemTabList.UIDonorsTabPage;
            WpfButton uICreateNewDonorButton = this.UIMainWindowWindow.UIItemTabList.UIDonorsTabPage.UICreateNewDonorButton;
            WpfEdit uIItemEdit = this.UICreateNewDonorWindow.UIItemEdit;
            WpfEdit uIItemEdit1 = this.UICreateNewDonorWindow.UIItemEdit1;
            WpfEdit uIItemEdit2 = this.UICreateNewDonorWindow.UIItemEdit2;
            WpfEdit uIItemEdit3 = this.UICreateNewDonorWindow.UIItemEdit3;
            WpfWindow uICreateNewDonorWindow = this.UICreateNewDonorWindow;
            WpfComboBox uIDTypeComboBox = this.UICreateNewDonorWindow.UIDTypeComboBox;
            WpfButton uIAddDonorButton = this.UICreateNewDonorWindow.UIAddDonorButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            WpfEdit uIItemEdit4 = this.UICreateIndividualContWindow.UIItemEdit;
            WpfEdit uIItemEdit11 = this.UICreateIndividualContWindow.UIItemEdit1;
            WpfEdit uIItemEdit21 = this.UICreateIndividualContWindow.UIItemEdit2;
            WpfEdit uIItemEdit31 = this.UICreateIndividualContWindow.UIItemEdit3;
            WpfButton uIAddContactButton = this.UICreateIndividualContWindow.UIAddContactButton;
            WpfTabPage uIInKindItemTabPage = this.UIMainWindowWindow.UIItemTabList.UIInKindItemTabPage;
            WinButton uICloseButton = this.UIMainWindowWindow1.UICloseButton;
            #endregion

            // Launch '%USERPROFILE%\Desktop\Spring2016\Software Engineering 3\FCS-Funding-2\FCS-Project\FCS_Funding_WPF\FCS_Funding\bin\Debug\FCS_Funding.exe'
            ApplicationUnderTest uILoginWindow = ApplicationUnderTest.Launch(this.TestInsertDonorIndividualParams.UILoginWindowExePath, this.TestInsertDonorIndividualParams.UILoginWindowAlternateExePath);

            // Type 'admin' in 'Username' text box
            uIUsernameEdit.Text = this.TestInsertDonorIndividualParams.UIUsernameEditText;

            // Type '{Tab}' in 'Username' text box
            Keyboard.SendKeys(uIUsernameEdit, this.TestInsertDonorIndividualParams.UIUsernameEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.TestInsertDonorIndividualParams.UIPasswordEditSendKeys, true);

            // Click 'Login' button
            Mouse.Click(uILoginButton, new Point(124, 38));

            // Click 'Donors' tab
            Mouse.Click(uIDonorsTabPage, new Point(148, 50));

            // Click 'Create New Donor' button
            Mouse.Click(uICreateNewDonorButton, new Point(187, 36));

            // Type '123 Miracle St' in text box numbered 2 in 'CreateNewDonor' window
            uIItemEdit.Text = this.TestInsertDonorIndividualParams.UIItemEditText;

            // Type 'UT' in text box numbered 4 in 'CreateNewDonor' window
            uIItemEdit1.Text = this.TestInsertDonorIndividualParams.UIItemEdit1Text;

            // Type '{Tab}' in text box numbered 4 in 'CreateNewDonor' window
            Keyboard.SendKeys(uIItemEdit1, this.TestInsertDonorIndividualParams.UIItemEdit1SendKeys, ModifierKeys.None);

            // Type 'North Salt Lake' in text box numbered 5 in 'CreateNewDonor' window
            uIItemEdit2.Text = this.TestInsertDonorIndividualParams.UIItemEdit2Text;

            // Type '{Tab}' in text box numbered 5 in 'CreateNewDonor' window
            Keyboard.SendKeys(uIItemEdit2, this.TestInsertDonorIndividualParams.UIItemEdit2SendKeys, ModifierKeys.None);

            // Type '84054' in text box numbered 6 in 'CreateNewDonor' window
            uIItemEdit3.Text = this.TestInsertDonorIndividualParams.UIItemEdit3Text;

            // Click 'CreateNewDonor' window
            Mouse.Click(uICreateNewDonorWindow, new Point(1199, 700));

            // Select 'Individual' in 'dType' combo box
            uIDTypeComboBox.SelectedItem = this.TestInsertDonorIndividualParams.UIDTypeComboBoxSelectedItem;

            // Click 'CreateNewDonor' window
            Mouse.Click(uICreateNewDonorWindow, new Point(946, 888));

            // Click 'Add Donor' button
            Mouse.Click(uIAddDonorButton, new Point(136, 32));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(32, 24));

            // Type 'Santa' in text box
            uIItemEdit4.Text = this.TestInsertDonorIndividualParams.UIItemEditText1;

            // Type '{Tab}' in text box
            Keyboard.SendKeys(uIItemEdit4, this.TestInsertDonorIndividualParams.UIItemEditSendKeys, ModifierKeys.None);

            // Type 'Claus' in text box numbered 2 in 'CreateIndividualContact' window
            uIItemEdit11.Text = this.TestInsertDonorIndividualParams.UIItemEdit1Text1;

            // Type '{Tab}' in text box numbered 2 in 'CreateIndividualContact' window
            Keyboard.SendKeys(uIItemEdit11, this.TestInsertDonorIndividualParams.UIItemEdit1SendKeys1, ModifierKeys.None);

            // Type '8017776666' in text box numbered 3 in 'CreateIndividualContact' window
            uIItemEdit21.Text = this.TestInsertDonorIndividualParams.UIItemEdit2Text1;

            // Type 'pwnzanator@pwned.me' in text box numbered 4 in 'CreateIndividualContact' window
            uIItemEdit31.Text = this.TestInsertDonorIndividualParams.UIItemEdit3Text1;

            // Click 'Add Contact' button
            Mouse.Click(uIAddContactButton, new Point(131, 39));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(77, 20));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(53, 18));

            // Click 'In-Kind Item' tab
            Mouse.Click(uIInKindItemTabPage, new Point(94, 30));

            // Click 'Donors' tab
            Mouse.Click(uIDonorsTabPage, new Point(165, 35));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(31, 36));
        }
        
        /// <summary>
        /// Inserted a donor with no data.
        /// </summary>
        public void TestInsertDonorAnonymous()
        {
            #region Variable Declarations
            WpfEdit uIUsernameEdit = this.UILoginWindow.UIUsernameEdit;
            WpfEdit uIPasswordEdit = this.UILoginWindow.UIPasswordEdit;
            WpfButton uILoginButton = this.UILoginWindow.UILoginButton;
            WpfTabPage uIDonorsTabPage = this.UIMainWindowWindow.UIItemTabList.UIDonorsTabPage;
            WpfButton uICreateNewDonorButton = this.UIMainWindowWindow.UIItemTabList.UIDonorsTabPage.UICreateNewDonorButton;
            WpfComboBox uIDTypeComboBox = this.UICreateNewDonorWindow.UIDTypeComboBox;
            WpfButton uIAddDonorButton = this.UICreateNewDonorWindow.UIAddDonorButton;
            WpfTabPage uIInKindItemTabPage = this.UIMainWindowWindow.UIItemTabList.UIInKindItemTabPage;
            WinButton uICloseButton = this.UIMainWindowWindow1.UICloseButton;
            #endregion

            // Launch '%USERPROFILE%\Desktop\Spring2016\Software Engineering 3\FCS-Funding-2\FCS-Project\FCS_Funding_WPF\FCS_Funding\bin\Debug\FCS_Funding.exe'
            ApplicationUnderTest uILoginWindow = ApplicationUnderTest.Launch(this.TestInsertDonorAnonymousParams.UILoginWindowExePath, this.TestInsertDonorAnonymousParams.UILoginWindowAlternateExePath);

            // Type 'admin' in 'Username' text box
            uIUsernameEdit.Text = this.TestInsertDonorAnonymousParams.UIUsernameEditText;

            // Type '{Tab}' in 'Username' text box
            Keyboard.SendKeys(uIUsernameEdit, this.TestInsertDonorAnonymousParams.UIUsernameEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.TestInsertDonorAnonymousParams.UIPasswordEditSendKeys, true);

            // Click 'Login' button
            Mouse.Click(uILoginButton, new Point(115, 48));

            // Click 'Donors' tab
            Mouse.Click(uIDonorsTabPage, new Point(105, 28));

            // Click 'Create New Donor' button
            Mouse.Click(uICreateNewDonorButton, new Point(54, 43));

            // Select 'Anonymous' in 'dType' combo box
            uIDTypeComboBox.SelectedItem = this.TestInsertDonorAnonymousParams.UIDTypeComboBoxSelectedItem;

            // Click 'Add Donor' button
            Mouse.Click(uIAddDonorButton, new Point(161, 41));

            // Click 'In-Kind Item' tab
            Mouse.Click(uIInKindItemTabPage, new Point(154, 20));

            // Click 'Donors' tab
            Mouse.Click(uIDonorsTabPage, new Point(117, 54));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(57, 25));
        }
        
        /// <summary>
        /// Tested inserting a donor that is a government organization.
        /// </summary>
        public void TestInsertDonorGovernment()
        {
            #region Variable Declarations
            WpfEdit uIUsernameEdit = this.UILoginWindow.UIUsernameEdit;
            WpfEdit uIPasswordEdit = this.UILoginWindow.UIPasswordEdit;
            WpfButton uILoginButton = this.UILoginWindow.UILoginButton;
            WpfTabPage uIDonorsTabPage = this.UIMainWindowWindow.UIItemTabList.UIDonorsTabPage;
            WpfButton uICreateNewDonorButton = this.UIMainWindowWindow.UIItemTabList.UIDonorsTabPage.UICreateNewDonorButton;
            WpfEdit uIItemEdit4 = this.UICreateNewDonorWindow.UIItemEdit4;
            WpfEdit uIItemEdit5 = this.UICreateNewDonorWindow.UIItemEdit5;
            WpfEdit uIItemEdit = this.UICreateNewDonorWindow.UIItemEdit;
            WpfEdit uIItemEdit1 = this.UICreateNewDonorWindow.UIItemEdit1;
            WpfEdit uIItemEdit2 = this.UICreateNewDonorWindow.UIItemEdit2;
            WpfEdit uIItemEdit3 = this.UICreateNewDonorWindow.UIItemEdit3;
            WpfComboBox uIDTypeComboBox = this.UICreateNewDonorWindow.UIDTypeComboBox;
            WpfButton uIAddDonorButton = this.UICreateNewDonorWindow.UIAddDonorButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            WpfTabPage uIInKindItemTabPage = this.UIMainWindowWindow.UIItemTabList.UIInKindItemTabPage;
            WpfWindow uIMainWindowWindow = this.UIMainWindowWindow;
            WinButton uICloseButton = this.UIMainWindowWindow1.UICloseButton;
            #endregion

            // Launch '%USERPROFILE%\Desktop\Spring2016\Software Engineering 3\FCS-Funding-2\FCS-Project\FCS_Funding_WPF\FCS_Funding\bin\Debug\FCS_Funding.exe'
            ApplicationUnderTest uILoginWindow = ApplicationUnderTest.Launch(this.TestInsertDonorGovernmentParams.UILoginWindowExePath, this.TestInsertDonorGovernmentParams.UILoginWindowAlternateExePath);

            // Type 'admin' in 'Username' text box
            uIUsernameEdit.Text = this.TestInsertDonorGovernmentParams.UIUsernameEditText;

            // Type '{Tab}' in 'Username' text box
            Keyboard.SendKeys(uIUsernameEdit, this.TestInsertDonorGovernmentParams.UIUsernameEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.TestInsertDonorGovernmentParams.UIPasswordEditSendKeys, true);

            // Click 'Login' button
            Mouse.Click(uILoginButton, new Point(61, 38));

            // Click 'Donors' tab
            Mouse.Click(uIDonorsTabPage, new Point(157, 37));

            // Click 'Create New Donor' button
            Mouse.Click(uICreateNewDonorButton, new Point(192, 27));

            // Type 'Hill Air Force Base' in text box
            uIItemEdit4.Text = this.TestInsertDonorGovernmentParams.UIItemEdit4Text;

            // Type '{Tab}' in text box
            Keyboard.SendKeys(uIItemEdit5, this.TestInsertDonorGovernmentParams.UIItemEdit5SendKeys, ModifierKeys.None);

            // Type '123 Good Guy Ln' in text box numbered 2 in 'CreateNewDonor' window
            uIItemEdit.Text = this.TestInsertDonorGovernmentParams.UIItemEditText;

            // Type 'UT' in text box numbered 4 in 'CreateNewDonor' window
            uIItemEdit1.Text = this.TestInsertDonorGovernmentParams.UIItemEdit1Text;

            // Type '{Tab}' in text box numbered 4 in 'CreateNewDonor' window
            Keyboard.SendKeys(uIItemEdit1, this.TestInsertDonorGovernmentParams.UIItemEdit1SendKeys, ModifierKeys.None);

            // Type 'Clearfield' in text box numbered 5 in 'CreateNewDonor' window
            uIItemEdit2.Text = this.TestInsertDonorGovernmentParams.UIItemEdit2Text;

            // Type '{Tab}' in text box numbered 5 in 'CreateNewDonor' window
            Keyboard.SendKeys(uIItemEdit2, this.TestInsertDonorGovernmentParams.UIItemEdit2SendKeys, ModifierKeys.None);

            // Type '89745' in text box numbered 6 in 'CreateNewDonor' window
            uIItemEdit3.Text = this.TestInsertDonorGovernmentParams.UIItemEdit3Text;

            // Select 'Government' in 'dType' combo box
            uIDTypeComboBox.SelectedItem = this.TestInsertDonorGovernmentParams.UIDTypeComboBoxSelectedItem;

            // Click 'Add Donor' button
            Mouse.Click(uIAddDonorButton, new Point(124, 27));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(19, 16));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(46, 37));

            // Click 'In-Kind Item' tab
            Mouse.Click(uIInKindItemTabPage, new Point(122, 33));

            // Click 'Donors' tab
            Mouse.Click(uIDonorsTabPage, new Point(98, 40));

            // Click 'MainWindow' window
            Mouse.Click(uIMainWindowWindow, new Point(1926, 24));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(47, 23));
        }
        
        /// <summary>
        /// TestInsertGrantProposalGovernment - Use 'TestInsertGrantProposalGovernmentParams' to pass parameters into this method.
        /// </summary>
        public void TestInsertGrantProposalGovernment()
        {
            #region Variable Declarations
            WpfEdit uIUsernameEdit = this.UILoginWindow.UIUsernameEdit;
            WpfEdit uIPasswordEdit = this.UILoginWindow.UIPasswordEdit;
            WpfEdit uIItemEdit = this.UICreateGrantProposalWindow.UIItemEdit;
            #endregion

            // Type 'Admin' in 'Username' text box
            uIUsernameEdit.Text = this.TestInsertGrantProposalGovernmentParams.UIUsernameEditText;

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.TestInsertGrantProposalGovernmentParams.UIPasswordEditSendKeys, true);

            // Type 'Loving Government Grant Name' in text box
            uIItemEdit.Text = this.TestInsertGrantProposalGovernmentParams.UIItemEditText;
        }
        
        /// <summary>
        /// TestInsertInKindItemGovernment - Use 'TestInsertInKindItemGovernmentParams' to pass parameters into this method.
        /// </summary>
        public void TestInsertInKindItemGovernment()
        {
            #region Variable Declarations
            WpfEdit uIUsernameEdit = this.UILoginWindow.UIUsernameEdit;
            WpfEdit uIPasswordEdit = this.UILoginWindow.UIPasswordEdit;
            WpfEdit uIItemEdit = this.UIAddInKindItemWindow.UIItemEdit;
            WpfEdit uIItemEdit1 = this.UIAddInKindItemWindow.UIItemEdit1;
            #endregion

            // Type 'Admin' in 'Username' text box
            uIUsernameEdit.Text = this.TestInsertInKindItemGovernmentParams.UIUsernameEditText;

            // Type '{Tab}' in 'Username' text box
            Keyboard.SendKeys(uIUsernameEdit, this.TestInsertInKindItemGovernmentParams.UIUsernameEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.TestInsertInKindItemGovernmentParams.UIPasswordEditSendKeys, true);

            // Type 'Sofa' in text box
            uIItemEdit.Text = this.TestInsertInKindItemGovernmentParams.UIItemEditText;

            // Type '{Tab}' in text box
            Keyboard.SendKeys(uIItemEdit, this.TestInsertInKindItemGovernmentParams.UIItemEditSendKeys, ModifierKeys.None);

            // Type 'This is a very nice test sofa.  ' in text box numbered 2 in 'AddInKindItem' window
            uIItemEdit1.Text = this.TestInsertInKindItemGovernmentParams.UIItemEdit1Text;
        }
        
        #region Properties
        public virtual LoginTestParams LoginTestParams
        {
            get
            {
                if ((this.mLoginTestParams == null))
                {
                    this.mLoginTestParams = new LoginTestParams();
                }
                return this.mLoginTestParams;
            }
        }
        
        public virtual TestInsertPatientParams TestInsertPatientParams
        {
            get
            {
                if ((this.mTestInsertPatientParams == null))
                {
                    this.mTestInsertPatientParams = new TestInsertPatientParams();
                }
                return this.mTestInsertPatientParams;
            }
        }
        
        public virtual TestInsertDonorIndividualParams TestInsertDonorIndividualParams
        {
            get
            {
                if ((this.mTestInsertDonorIndividualParams == null))
                {
                    this.mTestInsertDonorIndividualParams = new TestInsertDonorIndividualParams();
                }
                return this.mTestInsertDonorIndividualParams;
            }
        }
        
        public virtual TestInsertDonorAnonymousParams TestInsertDonorAnonymousParams
        {
            get
            {
                if ((this.mTestInsertDonorAnonymousParams == null))
                {
                    this.mTestInsertDonorAnonymousParams = new TestInsertDonorAnonymousParams();
                }
                return this.mTestInsertDonorAnonymousParams;
            }
        }
        
        public virtual TestInsertDonorGovernmentParams TestInsertDonorGovernmentParams
        {
            get
            {
                if ((this.mTestInsertDonorGovernmentParams == null))
                {
                    this.mTestInsertDonorGovernmentParams = new TestInsertDonorGovernmentParams();
                }
                return this.mTestInsertDonorGovernmentParams;
            }
        }
        
        public virtual TestInsertGrantProposalGovernmentParams TestInsertGrantProposalGovernmentParams
        {
            get
            {
                if ((this.mTestInsertGrantProposalGovernmentParams == null))
                {
                    this.mTestInsertGrantProposalGovernmentParams = new TestInsertGrantProposalGovernmentParams();
                }
                return this.mTestInsertGrantProposalGovernmentParams;
            }
        }
        
        public virtual TestInsertInKindItemGovernmentParams TestInsertInKindItemGovernmentParams
        {
            get
            {
                if ((this.mTestInsertInKindItemGovernmentParams == null))
                {
                    this.mTestInsertInKindItemGovernmentParams = new TestInsertInKindItemGovernmentParams();
                }
                return this.mTestInsertInKindItemGovernmentParams;
            }
        }
        
        public UILoginWindow UILoginWindow
        {
            get
            {
                if ((this.mUILoginWindow == null))
                {
                    this.mUILoginWindow = new UILoginWindow();
                }
                return this.mUILoginWindow;
            }
        }
        
        public UIMainWindowWindow UIMainWindowWindow
        {
            get
            {
                if ((this.mUIMainWindowWindow == null))
                {
                    this.mUIMainWindowWindow = new UIMainWindowWindow();
                }
                return this.mUIMainWindowWindow;
            }
        }
        
        public UICreateNewPatientWindow UICreateNewPatientWindow
        {
            get
            {
                if ((this.mUICreateNewPatientWindow == null))
                {
                    this.mUICreateNewPatientWindow = new UICreateNewPatientWindow();
                }
                return this.mUICreateNewPatientWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow();
                }
                return this.mUIOKWindow;
            }
        }
        
        public UICreateHouseholdWindow UICreateHouseholdWindow
        {
            get
            {
                if ((this.mUICreateHouseholdWindow == null))
                {
                    this.mUICreateHouseholdWindow = new UICreateHouseholdWindow();
                }
                return this.mUICreateHouseholdWindow;
            }
        }
        
        public UICreateNewDonorWindow UICreateNewDonorWindow
        {
            get
            {
                if ((this.mUICreateNewDonorWindow == null))
                {
                    this.mUICreateNewDonorWindow = new UICreateNewDonorWindow();
                }
                return this.mUICreateNewDonorWindow;
            }
        }
        
        public UICreateIndividualContWindow UICreateIndividualContWindow
        {
            get
            {
                if ((this.mUICreateIndividualContWindow == null))
                {
                    this.mUICreateIndividualContWindow = new UICreateIndividualContWindow();
                }
                return this.mUICreateIndividualContWindow;
            }
        }
        
        public UIMainWindowWindow1 UIMainWindowWindow1
        {
            get
            {
                if ((this.mUIMainWindowWindow1 == null))
                {
                    this.mUIMainWindowWindow1 = new UIMainWindowWindow1();
                }
                return this.mUIMainWindowWindow1;
            }
        }
        
        public UICreateGrantProposalWindow UICreateGrantProposalWindow
        {
            get
            {
                if ((this.mUICreateGrantProposalWindow == null))
                {
                    this.mUICreateGrantProposalWindow = new UICreateGrantProposalWindow();
                }
                return this.mUICreateGrantProposalWindow;
            }
        }
        
        public UIAddInKindItemWindow UIAddInKindItemWindow
        {
            get
            {
                if ((this.mUIAddInKindItemWindow == null))
                {
                    this.mUIAddInKindItemWindow = new UIAddInKindItemWindow();
                }
                return this.mUIAddInKindItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private LoginTestParams mLoginTestParams;
        
        private TestInsertPatientParams mTestInsertPatientParams;
        
        private TestInsertDonorIndividualParams mTestInsertDonorIndividualParams;
        
        private TestInsertDonorAnonymousParams mTestInsertDonorAnonymousParams;
        
        private TestInsertDonorGovernmentParams mTestInsertDonorGovernmentParams;
        
        private TestInsertGrantProposalGovernmentParams mTestInsertGrantProposalGovernmentParams;
        
        private TestInsertInKindItemGovernmentParams mTestInsertInKindItemGovernmentParams;
        
        private UILoginWindow mUILoginWindow;
        
        private UIMainWindowWindow mUIMainWindowWindow;
        
        private UICreateNewPatientWindow mUICreateNewPatientWindow;
        
        private UIOKWindow mUIOKWindow;
        
        private UICreateHouseholdWindow mUICreateHouseholdWindow;
        
        private UICreateNewDonorWindow mUICreateNewDonorWindow;
        
        private UICreateIndividualContWindow mUICreateIndividualContWindow;
        
        private UIMainWindowWindow1 mUIMainWindowWindow1;
        
        private UICreateGrantProposalWindow mUICreateGrantProposalWindow;
        
        private UIAddInKindItemWindow mUIAddInKindItemWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoginTest'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class LoginTestParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%USERPROFILE%\Desktop\Spring2016\Software Engineering 3\FCS-Funding-2\FCS-Project\FCS_Funding_WPF\FCS_Funding\bin\Debug\FCS_Funding.exe'
        /// </summary>
        public string UILoginWindowExePath = "C:\\Users\\Kenneth\\Desktop\\Spring2016\\Software Engineering 3\\FCS-Funding-2\\FCS-Proj" +
            "ect\\FCS_Funding_WPF\\FCS_Funding\\bin\\Debug\\FCS_Funding.exe";
        
        /// <summary>
        /// Launch '%USERPROFILE%\Desktop\Spring2016\Software Engineering 3\FCS-Funding-2\FCS-Project\FCS_Funding_WPF\FCS_Funding\bin\Debug\FCS_Funding.exe'
        /// </summary>
        public string UILoginWindowAlternateExePath = "%USERPROFILE%\\Desktop\\Spring2016\\Software Engineering 3\\FCS-Funding-2\\FCS-Project" +
            "\\FCS_Funding_WPF\\FCS_Funding\\bin\\Debug\\FCS_Funding.exe";
        
        /// <summary>
        /// Type 'admin' in 'Username' text box
        /// </summary>
        public string UIUsernameEditText = "admin";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "NyBJ9O1fhPe6fVpGjzOJroVoW2H5adUk";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestInsertPatient'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class TestInsertPatientParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%USERPROFILE%\Desktop\Spring2016\Software Engineering 3\FCS-Funding-2\FCS-Project\FCS_Funding_WPF\FCS_Funding\bin\Debug\FCS_Funding.exe'
        /// </summary>
        public string UILoginWindowExePath = "C:\\Users\\Kenneth\\Desktop\\Spring2016\\Software Engineering 3\\FCS-Funding-2\\FCS-Proj" +
            "ect\\FCS_Funding_WPF\\FCS_Funding\\bin\\Debug\\FCS_Funding.exe";
        
        /// <summary>
        /// Launch '%USERPROFILE%\Desktop\Spring2016\Software Engineering 3\FCS-Funding-2\FCS-Project\FCS_Funding_WPF\FCS_Funding\bin\Debug\FCS_Funding.exe'
        /// </summary>
        public string UILoginWindowAlternateExePath = "%USERPROFILE%\\Desktop\\Spring2016\\Software Engineering 3\\FCS-Funding-2\\FCS-Project" +
            "\\FCS_Funding_WPF\\FCS_Funding\\bin\\Debug\\FCS_Funding.exe";
        
        /// <summary>
        /// Type 'admin' in 'Username' text box
        /// </summary>
        public string UIUsernameEditText = "admin";
        
        /// <summary>
        /// Type '{Tab}' in 'Username' text box
        /// </summary>
        public string UIUsernameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "NyBJ9O1fhPe6fVpGjzOJroVoW2H5adUk";
        
        /// <summary>
        /// Type '50' in text box
        /// </summary>
        public string UIItemEditText = "50";
        
        /// <summary>
        /// Type 'codedUITest' in text box numbered 2 in 'CreateNewPatient' window
        /// </summary>
        public string UIItemEdit1Text = "codedUITest";
        
        /// <summary>
        /// Type 'lastName' in text box numbered 3 in 'CreateNewPatient' window
        /// </summary>
        public string UIItemEdit2Text = "lastName";
        
        /// <summary>
        /// Select 'Is Head of Household?' check box
        /// </summary>
        public bool UIIsHeadofHouseholdCheckBoxChecked = true;
        
        /// <summary>
        /// Select 'Female' in 'Gender' combo box
        /// </summary>
        public string UIGenderComboBoxSelectedItem = "Female";
        
        /// <summary>
        /// Select '45-54' in 'AgeGroup' combo box
        /// </summary>
        public string UIAgeGroupComboBoxSelectedItem = "45-54";
        
        /// <summary>
        /// Select 'Asian' in 'ethnicity' combo box
        /// </summary>
        public string UIEthnicityComboBoxSelectedItem = "Asian";
        
        /// <summary>
        /// Select 'First Member of Household?' check box
        /// </summary>
        public bool UIFirstMemberofHousehoCheckBoxChecked = true;
        
        /// <summary>
        /// Type 'Is head' in text box numbered 4 in 'CreateNewPatient' window
        /// </summary>
        public string UIItemEdit3Text = "Is head";
        
        /// <summary>
        /// Type '2' in text box
        /// </summary>
        public string UIItemEditText1 = "2";
        
        /// <summary>
        /// Type 'North Pole' in text box numbered 2 in 'CreateHousehold' window
        /// </summary>
        public string UIItemEdit1Text1 = "North Pole";
        
        /// <summary>
        /// Select '$35,000+' in 'income' combo box
        /// </summary>
        public string UIIncomeComboBoxSelectedItem = "$35,000+";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestInsertDonorIndividual'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class TestInsertDonorIndividualParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%USERPROFILE%\Desktop\Spring2016\Software Engineering 3\FCS-Funding-2\FCS-Project\FCS_Funding_WPF\FCS_Funding\bin\Debug\FCS_Funding.exe'
        /// </summary>
        public string UILoginWindowExePath = "C:\\Users\\Kenneth\\Desktop\\Spring2016\\Software Engineering 3\\FCS-Funding-2\\FCS-Proj" +
            "ect\\FCS_Funding_WPF\\FCS_Funding\\bin\\Debug\\FCS_Funding.exe";
        
        /// <summary>
        /// Launch '%USERPROFILE%\Desktop\Spring2016\Software Engineering 3\FCS-Funding-2\FCS-Project\FCS_Funding_WPF\FCS_Funding\bin\Debug\FCS_Funding.exe'
        /// </summary>
        public string UILoginWindowAlternateExePath = "%USERPROFILE%\\Desktop\\Spring2016\\Software Engineering 3\\FCS-Funding-2\\FCS-Project" +
            "\\FCS_Funding_WPF\\FCS_Funding\\bin\\Debug\\FCS_Funding.exe";
        
        /// <summary>
        /// Type 'admin' in 'Username' text box
        /// </summary>
        public string UIUsernameEditText = "admin";
        
        /// <summary>
        /// Type '{Tab}' in 'Username' text box
        /// </summary>
        public string UIUsernameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "NyBJ9O1fhPe6fVpGjzOJroVoW2H5adUk";
        
        /// <summary>
        /// Type '123 Miracle St' in text box numbered 2 in 'CreateNewDonor' window
        /// </summary>
        public string UIItemEditText = "123 Miracle St";
        
        /// <summary>
        /// Type 'UT' in text box numbered 4 in 'CreateNewDonor' window
        /// </summary>
        public string UIItemEdit1Text = "UT";
        
        /// <summary>
        /// Type '{Tab}' in text box numbered 4 in 'CreateNewDonor' window
        /// </summary>
        public string UIItemEdit1SendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'North Salt Lake' in text box numbered 5 in 'CreateNewDonor' window
        /// </summary>
        public string UIItemEdit2Text = "North Salt Lake";
        
        /// <summary>
        /// Type '{Tab}' in text box numbered 5 in 'CreateNewDonor' window
        /// </summary>
        public string UIItemEdit2SendKeys = "{Tab}";
        
        /// <summary>
        /// Type '84054' in text box numbered 6 in 'CreateNewDonor' window
        /// </summary>
        public string UIItemEdit3Text = "84054";
        
        /// <summary>
        /// Select 'Individual' in 'dType' combo box
        /// </summary>
        public string UIDTypeComboBoxSelectedItem = "Individual";
        
        /// <summary>
        /// Type 'Santa' in text box
        /// </summary>
        public string UIItemEditText1 = "Santa";
        
        /// <summary>
        /// Type '{Tab}' in text box
        /// </summary>
        public string UIItemEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Claus' in text box numbered 2 in 'CreateIndividualContact' window
        /// </summary>
        public string UIItemEdit1Text1 = "Claus";
        
        /// <summary>
        /// Type '{Tab}' in text box numbered 2 in 'CreateIndividualContact' window
        /// </summary>
        public string UIItemEdit1SendKeys1 = "{Tab}";
        
        /// <summary>
        /// Type '8017776666' in text box numbered 3 in 'CreateIndividualContact' window
        /// </summary>
        public string UIItemEdit2Text1 = "8017776666";
        
        /// <summary>
        /// Type 'pwnzanator@pwned.me' in text box numbered 4 in 'CreateIndividualContact' window
        /// </summary>
        public string UIItemEdit3Text1 = "pwnzanator@pwned.me";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestInsertDonorAnonymous'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class TestInsertDonorAnonymousParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%USERPROFILE%\Desktop\Spring2016\Software Engineering 3\FCS-Funding-2\FCS-Project\FCS_Funding_WPF\FCS_Funding\bin\Debug\FCS_Funding.exe'
        /// </summary>
        public string UILoginWindowExePath = "C:\\Users\\Kenneth\\Desktop\\Spring2016\\Software Engineering 3\\FCS-Funding-2\\FCS-Proj" +
            "ect\\FCS_Funding_WPF\\FCS_Funding\\bin\\Debug\\FCS_Funding.exe";
        
        /// <summary>
        /// Launch '%USERPROFILE%\Desktop\Spring2016\Software Engineering 3\FCS-Funding-2\FCS-Project\FCS_Funding_WPF\FCS_Funding\bin\Debug\FCS_Funding.exe'
        /// </summary>
        public string UILoginWindowAlternateExePath = "%USERPROFILE%\\Desktop\\Spring2016\\Software Engineering 3\\FCS-Funding-2\\FCS-Project" +
            "\\FCS_Funding_WPF\\FCS_Funding\\bin\\Debug\\FCS_Funding.exe";
        
        /// <summary>
        /// Type 'admin' in 'Username' text box
        /// </summary>
        public string UIUsernameEditText = "admin";
        
        /// <summary>
        /// Type '{Tab}' in 'Username' text box
        /// </summary>
        public string UIUsernameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "NyBJ9O1fhPe6fVpGjzOJroVoW2H5adUk";
        
        /// <summary>
        /// Select 'Anonymous' in 'dType' combo box
        /// </summary>
        public string UIDTypeComboBoxSelectedItem = "Anonymous";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestInsertDonorGovernment'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class TestInsertDonorGovernmentParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%USERPROFILE%\Desktop\Spring2016\Software Engineering 3\FCS-Funding-2\FCS-Project\FCS_Funding_WPF\FCS_Funding\bin\Debug\FCS_Funding.exe'
        /// </summary>
        public string UILoginWindowExePath = "C:\\Users\\Kenneth\\Desktop\\Spring2016\\Software Engineering 3\\FCS-Funding-2\\FCS-Proj" +
            "ect\\FCS_Funding_WPF\\FCS_Funding\\bin\\Debug\\FCS_Funding.exe";
        
        /// <summary>
        /// Launch '%USERPROFILE%\Desktop\Spring2016\Software Engineering 3\FCS-Funding-2\FCS-Project\FCS_Funding_WPF\FCS_Funding\bin\Debug\FCS_Funding.exe'
        /// </summary>
        public string UILoginWindowAlternateExePath = "%USERPROFILE%\\Desktop\\Spring2016\\Software Engineering 3\\FCS-Funding-2\\FCS-Project" +
            "\\FCS_Funding_WPF\\FCS_Funding\\bin\\Debug\\FCS_Funding.exe";
        
        /// <summary>
        /// Type 'admin' in 'Username' text box
        /// </summary>
        public string UIUsernameEditText = "admin";
        
        /// <summary>
        /// Type '{Tab}' in 'Username' text box
        /// </summary>
        public string UIUsernameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "NyBJ9O1fhPe6fVpGjzOJroVoW2H5adUk";
        
        /// <summary>
        /// Type 'Hill Air Force Base' in text box
        /// </summary>
        public string UIItemEdit4Text = "Hill Air Force Base";
        
        /// <summary>
        /// Type '{Tab}' in text box
        /// </summary>
        public string UIItemEdit5SendKeys = "{Tab}";
        
        /// <summary>
        /// Type '123 Good Guy Ln' in text box numbered 2 in 'CreateNewDonor' window
        /// </summary>
        public string UIItemEditText = "123 Good Guy Ln";
        
        /// <summary>
        /// Type 'UT' in text box numbered 4 in 'CreateNewDonor' window
        /// </summary>
        public string UIItemEdit1Text = "UT";
        
        /// <summary>
        /// Type '{Tab}' in text box numbered 4 in 'CreateNewDonor' window
        /// </summary>
        public string UIItemEdit1SendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Clearfield' in text box numbered 5 in 'CreateNewDonor' window
        /// </summary>
        public string UIItemEdit2Text = "Clearfield";
        
        /// <summary>
        /// Type '{Tab}' in text box numbered 5 in 'CreateNewDonor' window
        /// </summary>
        public string UIItemEdit2SendKeys = "{Tab}";
        
        /// <summary>
        /// Type '89745' in text box numbered 6 in 'CreateNewDonor' window
        /// </summary>
        public string UIItemEdit3Text = "89745";
        
        /// <summary>
        /// Select 'Government' in 'dType' combo box
        /// </summary>
        public string UIDTypeComboBoxSelectedItem = "Government";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestInsertGrantProposalGovernment'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class TestInsertGrantProposalGovernmentParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Admin' in 'Username' text box
        /// </summary>
        public string UIUsernameEditText = "Admin";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "NyBJ9O1fhPe6fVpGjzOJroVoW2H5adUk";
        
        /// <summary>
        /// Type 'Loving Government Grant Name' in text box
        /// </summary>
        public string UIItemEditText = "Loving Government Grant Name";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestInsertInKindItemGovernment'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class TestInsertInKindItemGovernmentParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Admin' in 'Username' text box
        /// </summary>
        public string UIUsernameEditText = "Admin";
        
        /// <summary>
        /// Type '{Tab}' in 'Username' text box
        /// </summary>
        public string UIUsernameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "NyBJ9O1fhPe6fVpGjzOJroVoW2H5adUk";
        
        /// <summary>
        /// Type 'Sofa' in text box
        /// </summary>
        public string UIItemEditText = "Sofa";
        
        /// <summary>
        /// Type '{Tab}' in text box
        /// </summary>
        public string UIItemEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'This is a very nice test sofa.  ' in text box numbered 2 in 'AddInKindItem' window
        /// </summary>
        public string UIItemEdit1Text = "This is a very nice test sofa.  ";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILoginWindow : WpfWindow
    {
        
        public UILoginWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Login";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Login");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "Username";
                    this.mUIUsernameEdit.WindowTitles.Add("Login");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public WpfEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "Password";
                    this.mUIPasswordEdit.WindowTitles.Add("Login");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public WpfButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUILoginButton.SearchProperties[WpfButton.PropertyNames.Name] = "Login";
                    this.mUILoginButton.WindowTitles.Add("Login");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIUsernameEdit;
        
        private WpfEdit mUIPasswordEdit;
        
        private WpfButton mUILoginButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMainWindowWindow : WpfWindow
    {
        
        public UIMainWindowWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIItemTabList UIItemTabList
        {
            get
            {
                if ((this.mUIItemTabList == null))
                {
                    this.mUIItemTabList = new UIItemTabList(this);
                }
                return this.mUIItemTabList;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTabList mUIItemTabList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemTabList : WpfTabList
    {
        
        public UIItemTabList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIPatientsTabPage UIPatientsTabPage
        {
            get
            {
                if ((this.mUIPatientsTabPage == null))
                {
                    this.mUIPatientsTabPage = new UIPatientsTabPage(this);
                }
                return this.mUIPatientsTabPage;
            }
        }
        
        public UIDonorsTabPage UIDonorsTabPage
        {
            get
            {
                if ((this.mUIDonorsTabPage == null))
                {
                    this.mUIDonorsTabPage = new UIDonorsTabPage(this);
                }
                return this.mUIDonorsTabPage;
            }
        }
        
        public WpfTabPage UIInKindItemTabPage
        {
            get
            {
                if ((this.mUIInKindItemTabPage == null))
                {
                    this.mUIInKindItemTabPage = new WpfTabPage(this);
                    #region Search Criteria
                    this.mUIInKindItemTabPage.SearchProperties[WpfTabPage.PropertyNames.Name] = "In-Kind Item";
                    this.mUIInKindItemTabPage.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIInKindItemTabPage;
            }
        }
        #endregion
        
        #region Fields
        private UIPatientsTabPage mUIPatientsTabPage;
        
        private UIDonorsTabPage mUIDonorsTabPage;
        
        private WpfTabPage mUIInKindItemTabPage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPatientsTabPage : WpfTabPage
    {
        
        public UIPatientsTabPage(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTabPage.PropertyNames.Name] = "Patients";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfButton UICreateNewPatientButton
        {
            get
            {
                if ((this.mUICreateNewPatientButton == null))
                {
                    this.mUICreateNewPatientButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUICreateNewPatientButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "CreateNewPat";
                    this.mUICreateNewPatientButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUICreateNewPatientButton;
            }
        }
        
        public WpfButton UIRefreshButton
        {
            get
            {
                if ((this.mUIRefreshButton == null))
                {
                    this.mUIRefreshButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIRefreshButton.SearchProperties[WpfButton.PropertyNames.Name] = "Refresh";
                    this.mUIRefreshButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIRefreshButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUICreateNewPatientButton;
        
        private WpfButton mUIRefreshButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDonorsTabPage : WpfTabPage
    {
        
        public UIDonorsTabPage(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTabPage.PropertyNames.Name] = "Donors";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfButton UICreateNewDonorButton
        {
            get
            {
                if ((this.mUICreateNewDonorButton == null))
                {
                    this.mUICreateNewDonorButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUICreateNewDonorButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "CreateNewDon";
                    this.mUICreateNewDonorButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUICreateNewDonorButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUICreateNewDonorButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICreateNewPatientWindow : WpfWindow
    {
        
        public UICreateNewPatientWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "CreateNewPatient";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("CreateNewPatient");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("CreateNewPatient");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        
        public WpfEdit UIItemEdit1
        {
            get
            {
                if ((this.mUIItemEdit1 == null))
                {
                    this.mUIItemEdit1 = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit1.SearchProperties[WpfEdit.PropertyNames.Instance] = "2";
                    this.mUIItemEdit1.WindowTitles.Add("CreateNewPatient");
                    #endregion
                }
                return this.mUIItemEdit1;
            }
        }
        
        public WpfEdit UIItemEdit2
        {
            get
            {
                if ((this.mUIItemEdit2 == null))
                {
                    this.mUIItemEdit2 = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit2.SearchProperties[WpfEdit.PropertyNames.Instance] = "3";
                    this.mUIItemEdit2.WindowTitles.Add("CreateNewPatient");
                    #endregion
                }
                return this.mUIItemEdit2;
            }
        }
        
        public WpfEdit UIItemEdit3
        {
            get
            {
                if ((this.mUIItemEdit3 == null))
                {
                    this.mUIItemEdit3 = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit3.SearchProperties[WpfEdit.PropertyNames.Instance] = "4";
                    this.mUIItemEdit3.WindowTitles.Add("CreateNewPatient");
                    #endregion
                }
                return this.mUIItemEdit3;
            }
        }
        
        public WpfCheckBox UIIsHeadofHouseholdCheckBox
        {
            get
            {
                if ((this.mUIIsHeadofHouseholdCheckBox == null))
                {
                    this.mUIIsHeadofHouseholdCheckBox = new WpfCheckBox(this);
                    #region Search Criteria
                    this.mUIIsHeadofHouseholdCheckBox.SearchProperties[WpfCheckBox.PropertyNames.Name] = "Is Head of Household?";
                    this.mUIIsHeadofHouseholdCheckBox.WindowTitles.Add("CreateNewPatient");
                    #endregion
                }
                return this.mUIIsHeadofHouseholdCheckBox;
            }
        }
        
        public WpfComboBox UIGenderComboBox
        {
            get
            {
                if ((this.mUIGenderComboBox == null))
                {
                    this.mUIGenderComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUIGenderComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "Gender";
                    this.mUIGenderComboBox.WindowTitles.Add("CreateNewPatient");
                    #endregion
                }
                return this.mUIGenderComboBox;
            }
        }
        
        public WpfComboBox UIAgeGroupComboBox
        {
            get
            {
                if ((this.mUIAgeGroupComboBox == null))
                {
                    this.mUIAgeGroupComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUIAgeGroupComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "AgeGroup";
                    this.mUIAgeGroupComboBox.WindowTitles.Add("CreateNewPatient");
                    #endregion
                }
                return this.mUIAgeGroupComboBox;
            }
        }
        
        public WpfComboBox UIEthnicityComboBox
        {
            get
            {
                if ((this.mUIEthnicityComboBox == null))
                {
                    this.mUIEthnicityComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUIEthnicityComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "ethnicity";
                    this.mUIEthnicityComboBox.WindowTitles.Add("CreateNewPatient");
                    #endregion
                }
                return this.mUIEthnicityComboBox;
            }
        }
        
        public WpfCheckBox UIFirstMemberofHousehoCheckBox
        {
            get
            {
                if ((this.mUIFirstMemberofHousehoCheckBox == null))
                {
                    this.mUIFirstMemberofHousehoCheckBox = new WpfCheckBox(this);
                    #region Search Criteria
                    this.mUIFirstMemberofHousehoCheckBox.SearchProperties[WpfCheckBox.PropertyNames.Name] = "First Member of Household?";
                    this.mUIFirstMemberofHousehoCheckBox.WindowTitles.Add("CreateNewPatient");
                    #endregion
                }
                return this.mUIFirstMemberofHousehoCheckBox;
            }
        }
        
        public WpfButton UIAddClientButton
        {
            get
            {
                if ((this.mUIAddClientButton == null))
                {
                    this.mUIAddClientButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIAddClientButton.SearchProperties[WpfButton.PropertyNames.Name] = "Add Client";
                    this.mUIAddClientButton.WindowTitles.Add("CreateNewPatient");
                    #endregion
                }
                return this.mUIAddClientButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIItemEdit;
        
        private WpfEdit mUIItemEdit1;
        
        private WpfEdit mUIItemEdit2;
        
        private WpfEdit mUIItemEdit3;
        
        private WpfCheckBox mUIIsHeadofHouseholdCheckBox;
        
        private WpfComboBox mUIGenderComboBox;
        
        private WpfComboBox mUIAgeGroupComboBox;
        
        private WpfComboBox mUIEthnicityComboBox;
        
        private WpfCheckBox mUIFirstMemberofHousehoCheckBox;
        
        private WpfButton mUIAddClientButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("OK");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("OK");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICreateHouseholdWindow : WpfWindow
    {
        
        public UICreateHouseholdWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "CreateHousehold";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("CreateHousehold");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("CreateHousehold");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        
        public WpfEdit UIItemEdit1
        {
            get
            {
                if ((this.mUIItemEdit1 == null))
                {
                    this.mUIItemEdit1 = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit1.SearchProperties[WpfEdit.PropertyNames.Instance] = "2";
                    this.mUIItemEdit1.WindowTitles.Add("CreateHousehold");
                    #endregion
                }
                return this.mUIItemEdit1;
            }
        }
        
        public WpfComboBox UIIncomeComboBox
        {
            get
            {
                if ((this.mUIIncomeComboBox == null))
                {
                    this.mUIIncomeComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUIIncomeComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "income";
                    this.mUIIncomeComboBox.WindowTitles.Add("CreateHousehold");
                    #endregion
                }
                return this.mUIIncomeComboBox;
            }
        }
        
        public WpfButton UIAddHouseholdButton
        {
            get
            {
                if ((this.mUIAddHouseholdButton == null))
                {
                    this.mUIAddHouseholdButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIAddHouseholdButton.SearchProperties[WpfButton.PropertyNames.Name] = "Add Household";
                    this.mUIAddHouseholdButton.WindowTitles.Add("CreateHousehold");
                    #endregion
                }
                return this.mUIAddHouseholdButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIItemEdit;
        
        private WpfEdit mUIItemEdit1;
        
        private WpfComboBox mUIIncomeComboBox;
        
        private WpfButton mUIAddHouseholdButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICreateNewDonorWindow : WpfWindow
    {
        
        public UICreateNewDonorWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "CreateNewDonor";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("CreateNewDonor");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchProperties[WpfEdit.PropertyNames.Instance] = "2";
                    this.mUIItemEdit.WindowTitles.Add("CreateNewDonor");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        
        public WpfEdit UIItemEdit1
        {
            get
            {
                if ((this.mUIItemEdit1 == null))
                {
                    this.mUIItemEdit1 = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit1.SearchProperties[WpfEdit.PropertyNames.Instance] = "4";
                    this.mUIItemEdit1.WindowTitles.Add("CreateNewDonor");
                    #endregion
                }
                return this.mUIItemEdit1;
            }
        }
        
        public WpfEdit UIItemEdit2
        {
            get
            {
                if ((this.mUIItemEdit2 == null))
                {
                    this.mUIItemEdit2 = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit2.SearchProperties[WpfEdit.PropertyNames.Instance] = "5";
                    this.mUIItemEdit2.WindowTitles.Add("CreateNewDonor");
                    #endregion
                }
                return this.mUIItemEdit2;
            }
        }
        
        public WpfEdit UIItemEdit3
        {
            get
            {
                if ((this.mUIItemEdit3 == null))
                {
                    this.mUIItemEdit3 = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit3.SearchProperties[WpfEdit.PropertyNames.Instance] = "6";
                    this.mUIItemEdit3.WindowTitles.Add("CreateNewDonor");
                    #endregion
                }
                return this.mUIItemEdit3;
            }
        }
        
        public WpfComboBox UIDTypeComboBox
        {
            get
            {
                if ((this.mUIDTypeComboBox == null))
                {
                    this.mUIDTypeComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUIDTypeComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "dType";
                    this.mUIDTypeComboBox.WindowTitles.Add("CreateNewDonor");
                    #endregion
                }
                return this.mUIDTypeComboBox;
            }
        }
        
        public WpfButton UIAddDonorButton
        {
            get
            {
                if ((this.mUIAddDonorButton == null))
                {
                    this.mUIAddDonorButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIAddDonorButton.SearchProperties[WpfButton.PropertyNames.Name] = "Add Donor";
                    this.mUIAddDonorButton.WindowTitles.Add("CreateNewDonor");
                    #endregion
                }
                return this.mUIAddDonorButton;
            }
        }
        
        public WpfEdit UIItemEdit4
        {
            get
            {
                if ((this.mUIItemEdit4 == null))
                {
                    this.mUIItemEdit4 = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit4.WindowTitles.Add("CreateNewDonor");
                    #endregion
                }
                return this.mUIItemEdit4;
            }
        }
        
        public WpfEdit UIItemEdit5
        {
            get
            {
                if ((this.mUIItemEdit5 == null))
                {
                    this.mUIItemEdit5 = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit5.WindowTitles.Add("CreateNewDonor");
                    #endregion
                }
                return this.mUIItemEdit5;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIItemEdit;
        
        private WpfEdit mUIItemEdit1;
        
        private WpfEdit mUIItemEdit2;
        
        private WpfEdit mUIItemEdit3;
        
        private WpfComboBox mUIDTypeComboBox;
        
        private WpfButton mUIAddDonorButton;
        
        private WpfEdit mUIItemEdit4;
        
        private WpfEdit mUIItemEdit5;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICreateIndividualContWindow : WpfWindow
    {
        
        public UICreateIndividualContWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "CreateIndividualContact";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("CreateIndividualContact");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("CreateIndividualContact");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        
        public WpfEdit UIItemEdit1
        {
            get
            {
                if ((this.mUIItemEdit1 == null))
                {
                    this.mUIItemEdit1 = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit1.SearchProperties[WpfEdit.PropertyNames.Instance] = "2";
                    this.mUIItemEdit1.WindowTitles.Add("CreateIndividualContact");
                    #endregion
                }
                return this.mUIItemEdit1;
            }
        }
        
        public WpfEdit UIItemEdit2
        {
            get
            {
                if ((this.mUIItemEdit2 == null))
                {
                    this.mUIItemEdit2 = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit2.SearchProperties[WpfEdit.PropertyNames.Instance] = "3";
                    this.mUIItemEdit2.WindowTitles.Add("CreateIndividualContact");
                    #endregion
                }
                return this.mUIItemEdit2;
            }
        }
        
        public WpfEdit UIItemEdit3
        {
            get
            {
                if ((this.mUIItemEdit3 == null))
                {
                    this.mUIItemEdit3 = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit3.SearchProperties[WpfEdit.PropertyNames.Instance] = "4";
                    this.mUIItemEdit3.WindowTitles.Add("CreateIndividualContact");
                    #endregion
                }
                return this.mUIItemEdit3;
            }
        }
        
        public WpfButton UIAddContactButton
        {
            get
            {
                if ((this.mUIAddContactButton == null))
                {
                    this.mUIAddContactButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIAddContactButton.SearchProperties[WpfButton.PropertyNames.Name] = "Add Contact";
                    this.mUIAddContactButton.WindowTitles.Add("CreateIndividualContact");
                    #endregion
                }
                return this.mUIAddContactButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIItemEdit;
        
        private WpfEdit mUIItemEdit1;
        
        private WpfEdit mUIItemEdit2;
        
        private WpfEdit mUIItemEdit3;
        
        private WpfButton mUIAddContactButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMainWindowWindow1 : WinWindow
    {
        
        public UIMainWindowWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICreateGrantProposalWindow : WpfWindow
    {
        
        public UICreateGrantProposalWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "CreateGrantProposal";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("CreateGrantProposal");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("CreateGrantProposal");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAddInKindItemWindow : WpfWindow
    {
        
        public UIAddInKindItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "AddInKindItem";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("AddInKindItem");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("AddInKindItem");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        
        public WpfEdit UIItemEdit1
        {
            get
            {
                if ((this.mUIItemEdit1 == null))
                {
                    this.mUIItemEdit1 = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit1.SearchProperties[WpfEdit.PropertyNames.Instance] = "2";
                    this.mUIItemEdit1.WindowTitles.Add("AddInKindItem");
                    #endregion
                }
                return this.mUIItemEdit1;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIItemEdit;
        
        private WpfEdit mUIItemEdit1;
        #endregion
    }
}
